### PR TITLE
added subdomain non-case-sensitive fix

### PR DESCRIPTION
**Pull request by GeorgeZhukov**

### CODE REVIEW

**Comment by sleekybadger** [comment]
@GeorgeZhukov thanks, IMHO i think we should transform to lowercase database values too. What do you think about it?

**Comment by GeorgeZhukov** [comment]
@lukyanovfedor well its a good idea too, but I'm just using this lib in my project and note that it works incorrectly with uppercase subdomains. by the way DNS doesn't recognize uppercase domains, so I thinks its a good idea to use only lowercase here. my models already has a validator for downcase domains. how you propose to transform to lowercase database values ? modify models of target applications?

**Comment by sleekybadger** [comment]
@GeorgeZhukov no, i thought about `lower` function, something like this: 

```
def domain_clause
  "LOWER(#{Detectify.config.domain_column}) = ?" if need_domain_clause?
end
```

**Comment by GeorgeZhukov** [comment]
You use LOWER for column name here, why? Did you mean lower function for value? If yes, we can implement it, but I'm not sure if its necessary.

**Pull request merged**
